name: First Workflow

on:     ##it will start automatically
  push:
    branches:
      - main
jobs:
    first-workflow:
        runs-on: ubuntu-latest
        steps:
            - name: First step
              run: |
                    echo "Hello, World!"
                    echo "Hello Again!"
