name: Cron workflow

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  cron-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Cron Workflow
        run: |
          echo "Hello Cron Job!"
          echo "This is automatically triggered every 5 minutes"
